name: awesome-text-deskew
channels:
  - conda-forge
dependencies:
  - python=3.8.18
  - pip=22.3.1
  - certifi=2022.12.7
  - setuptools=65.6.3
  - wheel=0.37.1
  - wincertstore=0.2

  # -c conda-forge
  # for jupyter
  - ipykernel==6.29.0
  - matplotlib=3.7.2

  - pip:
    - -r requirements.txt
